

// Macros to allow plugin options to be defined in unit tests
#define EMBER_AF_PLUGIN_SECURITY_SENSOR_TIME_BETWEEN_PRESSES_MS 500
#define EMBER_AF_PLUGIN_SECURITY_SENSOR_BUTTON_DEBOUNCE_TIME_MS 100
#define EMBER_AF_PLUGIN_SECURITY_SENSOR_NETWORK_LEAVE_TIME_MS   1000
#define EMBER_AF_PLUGIN_SECURITY_SENSOR_IAS_ZONE_ENDPOINT       1
